# Generated by Django 4.2 on 2023-05-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_salary_paid_date_alter_salary_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=5),
        ),
    ]
