# Generated by Django 4.2 on 2023-04-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sate',
            new_name='state',
        ),
    ]
